### ISSUE TITLE
license: suitable license for wrappid repositories

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/.github-private#2]
## Description

License is required for 
- packages - core, native-web, native-mobile, styles, service-core.
- wrappid-templates
- wrappid modules

Suggest which license to add with reasoning.

## Proposed License
MIT

#### Proposed by
@anantakumarghosh 

## Update 16th January 2024
- [x] Add MIT License in the below projects:
  - [x] wrappid/core#75
  - [x] wrappid/native-mobile#31
  - [x] wrappid/native-web#16
  - [x] wrappid/styles#16
  - [x] wrappid/service-core#15
  - [x] wrappid/wrappid-app#29
  - [x] wrappid/wrappid-service#25
  - [x] wrappid/wrappid-module#8
  - [x] wrappid/whatsapp#4

- [ ] wrappid/.github#9
- [ ] wrappid/.github#10
